runtime: nodejs16
instance_class: F1

automatic_scaling:
  max_instances: 1
  target_cpu_utilization: 0.85
  target_throughput_utilization: 0.85
  max_concurrent_requests: 80

includes:
- env_variables.yaml
